# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'iArrive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iArrive
  pod 'AFNetworking'
  pod 'Toast-Swift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'TTSegmentedControl'

  target 'iArriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iArriveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
