# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'iArrive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iArrive
  pod 'AFNetworking', '~> 3.0'
  pod 'Toast-Swift', '~> 5.0.0'

  target 'iArriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iArriveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
